### ISSUE TITLE
关于只爬取用户信息

### ISSUE THREAD

**Issue by hahajason** [dataabc/weibo-crawler#103]
大神，请问如何设置根据用户ID只爬取用户信息啊（不需要微博信息）？

**Comment by dataabc** [comment]
把since_date设置成未来的时间如2021-01-01

**Comment by hahajason** [comment]
我试过了，这个方法没办法大量爬取用户信息，一旦user_id_list.txt 里的id太多了的时候，爬取20多个用户信息之后就会有error。有什么方法解决吗？

**Comment by dataabc** [comment]
减缓爬行速度就可以了，修改start方法，原来代码：
```
            for user_config in self.user_config_list:
                ......
```
修改后的代码：
```
            user_count = 0
            user_count1 = random.randint(1, 5)
            random_users = random.randint(1, 5)
            for user_config in self.user_config_list:
                if (user_count - user_count1) % random_users == 0:
                    sleep(random.randint(6, 10))
                    user_count1 = user_count
                    random_users = random.randint(1, 5)
                user_count += 1
                ......
```
代码的意思是每爬1到5个用户，随机等待6到10秒，你可以根据实际情况，修改代码中的数字

**Comment by hahajason** [comment]
还是有问题（修改代码之前之后都会有）：
Traceback (most recent call last):
  File "C:\Users\ymh23\Downloads\weibo-crawler-master\weibo.py", line 1003, in get_pages
    self.print_user_info()
  File "C:\Users\ymh23\Downloads\weibo-crawler-master\weibo.py", line 529, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
Error:  'screen_name'
Traceback (most recent call last):
  File "C:\Users\ymh23\Downloads\weibo-crawler-master\weibo.py", line 1084, in start
    self.update_user_config_file(self.user_config_file_path)
  File "C:\Users\ymh23\Downloads\weibo-crawler-master\weibo.py", line 967, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'

**Comment by hahajason** [comment]
这次是爬了60多个就停了，我把sleep时间调成3-5秒

**Comment by dataabc** [comment]
如果出现错误，过一段时间再运行，或者换个账号
