### ISSUE TITLE
你好这个报错怎么解决'latin-1' codec can't encode characters in position 34-39: ordinal not in range(256)

### ISSUE THREAD

**Issue by KaishuoWang** [dataabc/weibo-crawler#111]
31条微博写入csv文件完毕,保存路径:
/home/pi/weibo-crawler/weibo//6081665760.csv
即将进行原创微博图片下载
'latin-1' codec can't encode characters in position 34-39: ordinal not in range(256)
Traceback (most recent call last):
  File "weibo.py", line 405, in download_files
    if not os.path.isdir(file_dir):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 34-39: ordinal not in range(256)
微博爬取完成，共爬取31条微博
信息抓取完毕

**Comment by dataabc** [comment]
感谢反馈。

是不是程序所在的文件夹名有特殊字符？可以换个文件夹，或者修改程序的405行为：
```
            if not os.path.isdir(file_dir.encode('utf-8').decode('latin1')):
```

如果还有问题，欢迎继续讨论

**Comment by KaishuoWang** [comment]
/home/pi/weibo-crawler
这个是程序所在的文件夹，应该没有特殊字符

修改之后的报错信息变成了这个样子
即将进行原创微博图片下载
'latin-1' codec can't encode characters in position 34-39: ordinal not in range(256)
Traceback (most recent call last):
  File "weibo.py", line 406, in download_files
    os.makedirs(file_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 34-39: ordinal not in range(256)
微博爬取完成，共爬取2条微博
信息抓取完毕

**Comment by dataabc** [comment]
应该是file_dir里有特殊字符，如果不是目录，可能是用户昵称。

再改回原来的代码，在原来的405行添加
```
            file_dir = file_dir.encode('utf-8').decode('latin1')
```

**Comment by KaishuoWang** [comment]
现在问题解决了，谢谢
