### ISSUE TITLE
请教如何将保存路径的昵称改为“id”

### ISSUE THREAD

**Issue by gudaost** [dataabc/weibo-crawler#112]
用户的昵称有时候是会修改的（虽然不太频繁），但每次改了都很麻烦，所以希望改成id，这个是确定不变的。
感觉应该是在这里修改：
def get_filepath(self, type):
        """获取结果文件路径"""
        try:            
            file_dir = save_path + os.sep + self.user['screen_name']
尝试把screen_name改成user_id，id，self.user_config['user_id']、str(self.user['id'])  等均不行，错误提示都一样
Error:  stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "X:\Program Files\Pic_Follow_Download_WeiBo_zhuanfa\weibo.py", line 1012, in get_pages
    self.get_user_info()
  File "X:\Program Files\Pic_Follow_Download_WeiBo_zhuanfa\weibo.py", line 259, in get_user_info
    self.user_to_database()
  File "X:\Program Files\Pic_Follow_Download_WeiBo_zhuanfa\weibo.py", line 205, in user_to_database
    self.user_to_csv()
  File "X:\Program Files\Pic_Follow_Download_WeiBo_zhuanfa\weibo.py", line 140, in user_to_csv
    if not os.path.isdir(file_dir):
  File "C:\Users\jinqi\AppData\Local\Programs\Python\Python38\lib\genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
信息抓取完毕

请教该怎么修改，多谢！

**Comment by dataabc** [comment]
和id没关系。
提示是file_dir为空，是在user_to_csv方法出现的，出错代码之前是
```
        file_dir = os.path.split(
            os.path.realpath(__file__))[0] + os.sep + 'weibo'
```
然后提示路径为空，即file_dir为空，是不是这行代码被修改成空的了？

**Comment by gudaost** [comment]
我汗……
之前参照您新版那个的设置，把这个增加了运行时增加路径参数（简化处理，没设置默认），结果这里再修改时，就出问题了。
已经搞定，麻烦了！
