### ISSUE TITLE
请问这个报错是什么原因导致的？

### ISSUE THREAD

**Issue by gudaost** [dataabc/weibo-crawler#113]
前面和后面爬取都正常，中间出现了这个
用户信息
Error:  'id'
Traceback (most recent call last):
  File "weibo.py", line 1013, in get_pages
    self.print_user_info()
  File "weibo.py", line 537, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
信息抓取完毕

**Comment by dataabc** [comment]
速度太快了，被暂时限制了。降速就可以了

**Comment by gudaost** [comment]
多谢！
