### ISSUE TITLE
建议：将description字段类型从VARCHAR(140)更改为LONGTEXT

### ISSUE THREAD

**Issue by loop0day** [dataabc/weibo-crawler#121]
OS: Windows 10 2004
Python: 3.8.5
PyMySQL: 0.10.1
MySQL Community Server: 8.0.21
weibo-crawler: ed32c68b7c8eccc1b3cc81696b3c548026e146e9

uid: 2166094271，报错信息如下：

> (1406, "Data too long for column 'description' at row 1")
Traceback (most recent call last):
  File ".\weibo.py", line 906, in mysql_insert
    cursor.executemany(
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\cursors.py", line 192, in executemany
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\cursors.py", line 192, in <genexpr>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\cursors.py", line 163, in execute
    result = self._query(query)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\cursors.py", line 321, in _query
    conn.query(q)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\connections.py", line 724, in _read_query_result
    result.read()
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "E:\Workspace\weibo-crawler\venv\lib\site-packages\pymysql\err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'description' at row 1")
MIIDII谜底信息写入MySQL数据库完毕
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
用户id：2166094271
用户昵称：MIIDII谜底
性别：女
生日：
所在地：
教育经历：
公司：
阳光信用：
注册时间：
微博数：8338
粉丝数：14098
关注数：103
url：https://m.weibo.cn/profile/2166094271
广州市猜想服饰有限公司
设计师原创品牌 -- 谜底，秉承着“让时尚与自然轻松地融为一体”的初衷，坚持环保理念，将时尚艺术完美结合独特剪裁工艺，让细节更精致。谜底，以服饰演绎心灵，让故事的生命再现：一年又一年，我们在世界每个温暖的角落，陶醉于设计大师的艺术之笔，源源不断的心灵故事和作品，融汇于崇尚自然与时尚女性的心灵和气质，演绎着自然、优雅和异域浪漫风情的一个又一个迷人的生活故事。
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
微博爬取完成，共爬取0条微博
信息抓取完毕
****************************************************************************************************

个人猜测是简介内容过长，将description字段类型更改为LONGTEXT后正常执行，这里是个BUG还是作者有其他的考虑？

**Comment by dataabc** [comment]
感谢建议。

非常好的建议，考虑过LONGTEXT类型，但是效率不如varchar，所以使用了varchar，后续会对description长度稍作调整。

再次感谢，如果还有问题欢迎继续讨论
