### ISSUE TITLE
您好，这个报错应该怎么修改呀？

### ISSUE THREAD

**Issue by Nicechair** [dataabc/weibo-crawler#16]
Error:  Expecting property name enclosed in double quotes: line 9 column 1 (char 172)
Traceback (most recent call last):
  File "D:/Anaconda3/weibo-crawler-master/weibo.py", line 807, in main
    config = json.loads(f.read())
  File "D:\Anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 172)

**Comment by dataabc** [comment]
应该是你的config.json格式不正确，比如使用了单引号，或者多了逗号等等，参考默认的config.json，修改后应该就可以运行了。

**Comment by dataabc** [comment]
感谢反馈，已添加对config.json格式的检测

**Comment by Nicechair** [comment]
> 感谢反馈，已添加对config.json格式的检测

谢谢你的解答^^请问图片和视频需要另外的步骤下载吗？运行了两次都只有csv文件生成，图片视频没有抓取下来欸（新手上路问题都很傻，请担待啦）
