### ISSUE TITLE
2218081121这个id不能获取

### ISSUE THREAD

**Issue by malagebidi** [dataabc/weibo-crawler#163]
```

> 2021-01-18 18:00:58,649 - ERROR - weibo.py[:1103] - 'id'
> Traceback (most recent call last):
>   File "weibo.py", line 1071, in get_pages
>     self.print_user_info()
>   File "weibo.py", line 582, in print_user_info
>     logger.info(u'用户id：%s', self.user['id'])
> KeyError: 'id'
> 

```

error.log的内容如上，我试了默认的迪丽热巴是可以爬取的。

**Comment by malagebidi** [comment]
设置cookie已解决。
