### ISSUE TITLE
这种报错是否为账号被封

### ISSUE THREAD

**Issue by Dossy1234** [dataabc/weibo-crawler#172]
Traceback (most recent call last):
  File "C:/Users/33490/Documents/Master/MSBA7012/project/weibo-crawler-master/weibo.py", line 1072, in get_pages
    self.print_user_info()
  File "C:/Users/33490/Documents/Master/MSBA7012/project/weibo-crawler-master/weibo.py", line 583, in print_user_info
    logger.info(u'用户id：%s', self.user['id'])
KeyError: 'id'
设置了300+的uid，第一个uid爬取了三十几页左右开始有这个报错，然后再运行都一直是这个报错了
想请问一下这个是我的账号被封禁了呢，遇到这种情况需要等待多久，有没有快速解决的办法比如更换cookie更换账号呀
感谢~

**Comment by dataabc** [comment]
感谢反馈。

应该是暂时的，大约一.天左右解封吧。建议放慢速度，过一段时间再运行。你可以尝试更换账号，我也不确定是否一定有效，因为这可能和ip也有关系。

如果还有问题欢迎继续讨论。
