### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by neallg** [dataabc/weibo-crawler#223]
我已经注意到这个错误好几天了，
可以修复吗？

`--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1098, in emit
    msg = self.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 942, in format
    return fmt.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not str
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 157, in main
    ret = method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 573, in runcode
    exec(code, self.locals)
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1641, in <module>
    main()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1635, in main
    wb.start()  # 爬取微博信息
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1604, in start
    self.get_pages()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1520, in get_pages
    self.print_user_info()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 673, in print_user_info
    logger.info(u'粉丝数：%d', self.user['followers_count'])
Message: '粉丝数：%d'
Arguments: ('7653.7万',)
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1098, in emit
    msg = self.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 942, in format
    return fmt.format(record)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 678, in format
    record.message = record.getMessage()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: %d format: a real number is required, not str
Call stack:
  File "<string>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 157, in main
    ret = method(*args, **kwargs)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\idlelib\run.py", line 573, in runcode
    exec(code, self.locals)
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1641, in <module>
    main()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1635, in main
    wb.start()  # 爬取微博信息
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1604, in start
    self.get_pages()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 1520, in get_pages
    self.print_user_info()
  File "C:\Users\User\Desktop\weibo-crawler-master\weibo.py", line 673, in print_user_info
    logger.info(u'粉丝数：%d', self.user['followers_count'])
Message: '粉丝数：%d'
Arguments: ('7653.7万',)`

**Comment by dataabc** [comment]
感谢反馈。已经修复了，如果还有错误，欢迎继续讨论，再次感谢。
