### ISSUE TITLE
--- Logging error ---TypeError: %d format: a number is required, not str

### ISSUE THREAD

**Issue by konglq1025** [dataabc/weibo-crawler#224]
大佬，最近出现了如楼上所说的错误，我的也出现了。

--- Logging error ---
Traceback (most recent call last):
  File "E:\python\anaconda3\lib\logging\__init__.py", line 983, in emit
    msg = self.format(record)
  File "E:\python\anaconda3\lib\logging\__init__.py", line 829, in format
    return fmt.format(record)
  File "E:\python\anaconda3\lib\logging\__init__.py", line 569, in format
    record.message = record.getMessage()
  File "E:\python\anaconda3\lib\logging\__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str

**Comment by dataabc** [comment]
已经修复了，感谢热心反馈。
