### ISSUE TITLE
 list index out of range报错

### ISSUE THREAD

**Issue by LY12emp** [dataabc/weibo-crawler#276]
2022-04-06 16:38:54,226 - ERROR - weibo.py[:1621] - list index out of range
Traceback (most recent call last):
  File "weibo.py", line 1585, in get_pages
    if(self.get_user_info() != 0):
  File "weibo.py", line 334, in get_user_info
    self.user_to_database()
  File "weibo.py", line 270, in user_to_database
    self.user_to_csv()
  File "weibo.py", line 218, in user_to_csv
    self.last_weibo_date = last_weibo_msg.split(' ')[1] if last_weibo_msg else self.user_config['since_date']
IndexError: list index out of range

好像1开头的id没问题，3和5开头都不行。

**Comment by dataabc** [comment]
可能是id不正确，或者被暂时限制了。
