### ISSUE TITLE
出现了这个，漏掉一条微博

### ISSUE THREAD

**Issue by JiMoDeJieFang** [dataabc/weibo-crawler#296]
2022-05-11 20:32:13,262 - ERROR - weibo.py[:752] - Extra data: line 112 column 2 (char 5454)
Traceback (most recent call last):
  File "weibo.py", line 743, in get_one_weibo
    weibo = self.get_long_weibo(weibo_id)
  File "weibo.py", line 330, in get_long_weibo
    js = json.loads(html, strict=False)
  File "D:\Software\Python\Python38\lib\json\__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "D:\Software\Python\Python38\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 112 column 2 (char 5454)

**Comment by dataabc** [comment]
更新到最新版本看看。

**Comment by JiMoDeJieFang** [comment]
> 更新到最新版本看看。

新版本和旧版本差别很大啊，可以下载之后把原来的weibo文件夹复制过去吗？会在原来的文件后面接着写吗

**Comment by dataabc** [comment]
应该是可以的。
