### ISSUE TITLE
爬一条用户信息要七八分钟正常吗？

### ISSUE THREAD

**Issue by Lu-qiuqiu** [dataabc/weibo-crawler#299]
用cmd爬一条用户信息（时间设到未来去）要七八分钟至少 这正常吗？

**Comment by Lu-qiuqiu** [comment]
有时候还会报这样的错误
[Errno 13] Permission denied: 'C:\\Users\\湫卢\\Desktop\\weibo-crawler-master\\weibo\\users.csv'
Traceback (most recent call last):
  File "C:\Users\湫卢\Desktop\weibo-crawler-master\weibo.py", line 1849, in get_pages
    if self.get_user_info() != 0:
  File "C:\Users\湫卢\Desktop\weibo-crawler-master\weibo.py", line 388, in get_user_info
    self.user_to_database()
  File "C:\Users\湫卢\Desktop\weibo-crawler-master\weibo.py", line 320, in user_to_database
    self.user_to_csv()
  File "C:\Users\湫卢\Desktop\weibo-crawler-master\weibo.py", line 259, in user_to_csv
    last_weibo_msg = csvutil.insert_or_update_user(
  File "C:\Users\湫卢\Desktop\weibo-crawler-master\util\csvutil.py", line 18, in insert_or_update_user
    with open(file_path, 'a', encoding='utf-8-sig', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\湫卢\\Desktop\\weibo-crawler-master\\weibo\\users.csv'

**Comment by Lu-qiuqiu** [comment]
> 用cmd爬一条用户信息（时间设到未来去）要七八分钟至少 这正常吗？

修正一下，是三四分钟

**Comment by dataabc** [comment]
应该是你打开csv文件了，导致出错，关掉就可以了。

**Comment by Lu-qiuqiu** [comment]
> 应该是你打开csv文件了，导致出错，关掉就可以了。

是的，关掉就正常了，但爬一个ID的用户信息要三四发钟是正常的吗？大佬

**Comment by dataabc** [comment]
之前应该没这么久，不确定是不是之前获取多了被限速。
