### ISSUE TITLE
您好，在python环境下的最后运行指令是什么呢？

### ISSUE THREAD

**Issue by ahalfer** [dataabc/weibo-crawler#324]
我在weibo-crawler的目录下输入指令python weibo.py 或者python -m weibo.py或者 python -m weibo都提示找不到模块。
显示Traceback (most recent call last):
  File "weibo.py", line 14, in <module>
    import sqlite3
  File "D:\anaconda\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "D:\anaconda\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed while importing _sqlite3: 找不到指定的模块。
尝试输入python -m weibo-crawler的命令，被提醒这是package而不是module。

**Comment by dataabc** [comment]
python weibo.py，应该是缺少了sqlite模块，安装上再看看

**Comment by ahalfer** [comment]
谢谢，根据教程去官网下载了Sqlite，成功备份了。一年前也用过weibo spider，双份感谢。
