### ISSUE TITLE
您好，在爬取的时候有几条微博会报错，请问是什么原因呢

### ISSUE THREAD

**Issue by 12414123123123** [dataabc/weibo-crawler#328]
list index out of range
Traceback (most recent call last):
  File "D:\demo\weibo-crawler\weibo.py", line 1075, in get_one_page
    w = w.get("card_group",[0])[0] or w
IndexError: list index out of range

**Comment by dataabc** [comment]
这个我也不确定。

**Comment by 12414123123123** [comment]
> 这个我也不确定。

我更新cookie后试了一下 还是会报错
list index out of range
Traceback (most recent call last):
File "D:\demo\weibo-crawler\weibo.py", line 1075, in get_one_page
w = w.get("card_group",[0])[0] or w
IndexError: list index out of range

**Comment by dataabc** [comment]
这部分代码是网友贡献的，用来检测cookie，如果报错可能cookie不正确，我现在不方便调试，不确定是代码错误还是cookie不正确，您如果方便可以使用现在的cookie在项目weibospider上，这个如果运行正确就是cookie没问题。

**Comment by 12414123123123** [comment]
> 

感谢大佬回复,我换到spider上使用没有出现问题
