### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by YTB-X** [dataabc/weibo-crawler#329]
'download_comment'
Traceback (most recent call last):
  File "/root/weibo-crawler/weibo.py", line 1980, in main
    wb = Weibo(config)
  File "/root/weibo-crawler/weibo.py", line 45, in __init__
    self.validate_config(config)
  File "/root/weibo-crawler/weibo.py", line 131, in validate_config
    if config[argument] != 0 and config[argument] != 1:
KeyError: 'download_comment'
root@aibug:~/weibo-crawler#
请问大佬是什么原因，谢谢啦

**Comment by dataabc** [comment]
可能是你使用的config.json过时了，下载最新的看看。

**Comment by YTB-X** [comment]
是里面内容格式过时了？





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2022年10月27日(星期四) 晚上7:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataabc/weibo-crawler] 运行报错 (Issue #329)





 
可能是你使用的config.json过时了，下载最新的看看。

**Comment by YTB-X** [comment]
我重新git后确实可以了，谢谢大佬了



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2022年10月28日(周五) 晚上9:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dataabc/weibo-crawler] 运行报错 (Issue #329)




 
看错误可能是过时了。
