### ISSUE TITLE
在外部调用weibo.py报错：TypeError: encode() argument 1 must be string, not None

### ISSUE THREAD

**Issue by AChaoZJU** [dataabc/weibo-crawler#34]
我在Node程序中调用weibo.py,代码如下：
```
//index.js
const spawn = require("child_process").spawn; 
const process = spawn('python',["./weibo.py"])
process.stdout.on('data', (data) => {
    console.log(`stdout: ${data}`);
});
process.stderr.on('data', (data) => {
    console.error(`stderr: ${data}`);
});
```
index.js和weibo.py在同一级目录下
执行命令
```
$ node index.js
```
报错如下:
```
stderr: Traceback (most recent call last):

stderr:   File "./weibo.py", line 947, in start
    self.get_pages()
  File "./weibo.py", line 888, in get_pages
    self.get_user_info()
  File "./weibo.py", line 200, in get_user_info
    user = self.standardize_info(user_info)
  File "./weibo.py", line 424, in standardize_info
    sys.stdout.encoding, "ignore").decode(sys.stdout.encoding)
TypeError: encode() argument 1 must be string, not None

stdout: ('Error: ', TypeError('encode() argument 1 must be string, not None',))
```
报错结果显示weibo.py第424行报错：
```
weibo[k] = v.replace(u"\u200b", "").encode(
                    sys.stdout.encoding, "ignore").decode(sys.stdout.encoding)
```
`sys.stdout.encoding`的值是None,引发了报错，那么能否用固定值替换`sys.stdout.encoding`

**Comment by dataabc** [comment]
可以。

尝试换成utf-8应该可以

**Comment by AChaoZJU** [comment]
@dataabc 替换成utf-8后，还是报错（如果直接运行python weibo.py, 程序还是能正常执行的）
```
$ node index.js
```
```
stderr: Traceback (most recent call last):

stderr:   File "./weibo.py", line 947, in start
    self.get_pages()
  File "./weibo.py", line 891, in get_pages
    self.print_user_info()
  File "./weibo.py", line 458, in print_user_info
    print(u'用户信息')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)

stdout: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
('Error: ', UnicodeEncodeError('ascii', u'\u7528\u6237\u4fe1\u606f', 0, 4, 'ordinal not in range(128)'))
```

**Comment by AChaoZJU** [comment]
@dataabc 
将需要被打印的字符串编码即可
```
print(u'用户信息')
```
替换成
```
print(u'用户信息'.encode('utf-8'))
```
即可消除报错
因为这些打印的行数太多，我直接将这些打印代码注释了。

**Comment by dataabc** [comment]
我又测试了下。
发现在不修改代码的时候也出现上述错误，解决方法除了上面替换成utf-8外，还需要注释掉所有的打印（print）代码，这样程序就可以正确运行了
