### ISSUE TITLE
报错  信息抓取完毕

### ISSUE THREAD

**Issue by specked2527** [dataabc/weibo-crawler#345]
HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=1005056103252147 (Caused by ProxyError('Cannot connect to proxy.', FileNotFoundError(2, 'No such file or directory')))
Traceback (most recent call last):
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 364, in connect
    self.sock = conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\connection.py", line 499, in _connect_tls_proxy
    socket = ssl_wrap_socket(
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\NAS\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

**Comment by dataabc** [comment]
有可能速度太快被限制或者运行时打开了csv文件。

**Comment by specked2527** [comment]
试了几次不行捏 （

![2023-02-26_015505](https://user-images.githubusercontent.com/124735279/221373003-8f64867f-854e-47d7-aa6a-51485a2afc09.png)

**Comment by dataabc** [comment]
可能要等几天，或者换个不同账号的cookie。

**Comment by twilight1024** [comment]
关闭代理就好了
