### ISSUE TITLE
只能爬取200页微博是怎么回事？

### ISSUE THREAD

**Issue by twilight1024** [dataabc/weibo-crawler#357]

**Comment by dataabc** [comment]
添加cookie看看。

**Comment by twilight1024** [comment]
您好，您的邮件我已经收到！若有其他问题我将通过邮件或电话等方式联系您！

**Comment by twilight1024** [comment]
> 

添加了之后还是不行

**Comment by twilight1024** [comment]
> 添加cookie看看。

可以了可以了

**Comment by twilight1024** [comment]
> 添加cookie看看。

stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "D:\weibo-crawler-master4\weibo-crawler-master\weibo.py", line 1883, in get_pages
    self.write_data(wrote_count)
  File "D:\weibo-crawler-master4\weibo-crawler-master\weibo.py", line 1836, in write_data
    self.write_csv(wrote_count)
  File "D:\weibo-crawler-master4\weibo-crawler-master\weibo.py", line 1293, in write_csv
    self.csv_helper(result_headers, result_data, file_path)
  File "D:\weibo-crawler-master4\weibo-crawler-master\weibo.py", line 1297, in csv_helper
    if not os.path.isfile(file_path):
  File "D:\anaconda\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
信息抓取完毕
****************************************************************************************************
这是怎么回事呀？

**Comment by UniversalRedBlue** [comment]
同问，添加了cookie之后还是不行

**Comment by twilight1024** [comment]
您好，您的邮件我已经收到！若有其他问题我将通过邮件或电话等方式联系您！

**Comment by dataabc** [comment]
是不是运行时删除了某些文件夹？

**Comment by UniversalRedBlue** [comment]
> 是不是运行时删除了某些文件夹？

使用weiboSpider就没问题了，感谢

**Comment by UniversalRedBlue** [comment]
使用weiboSpider解决问题了，感谢您




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chen ***@***.***&gt;; 
发送时间: 2023年11月30日(星期四) 凌晨1:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dataabc/weibo-crawler] 只能爬取200页微博是怎么回事？ (Issue #357)





 
是不是运行时删除了某些文件夹？
