### ISSUE TITLE
新版旧版都找不到日期

### ISSUE THREAD

**Issue by cnghw** [dataabc/weibo-crawler#369]
'since_date'
Traceback (most recent call last):
  File "C:\Users\cnghw\Desktop\weibo-crawler-masterN\weibo.py", line 1849, in get_pages
    if self.get_user_info() != 0:
  File "C:\Users\cnghw\Desktop\weibo-crawler-masterN\weibo.py", line 388, in get_user_info
    self.user_to_database()
  File "C:\Users\cnghw\Desktop\weibo-crawler-masterN\weibo.py", line 320, in user_to_database
    self.user_to_csv()
  File "C:\Users\cnghw\Desktop\weibo-crawler-masterN\weibo.py", line 266, in user_to_csv
    else self.user_config["since_date"]
KeyError: 'since_date'
信息抓取完毕
麻烦看看

**Comment by cnghw** [comment]
Progress:   0%|                                                                                | 0/334 [00:00<?, ?it/s]'card_group'
Traceback (most recent call last):
  File "C:\Users\cnghw\Desktop\weibo-crawler-masterN\weibo.py", line 1065, in get_one_page
    weibos = weibos[0]["card_group"]
KeyError: 'card_group'
Progress:   0%|▏                                                                       | 1/334 [00:00<02:52,  1.93it/s]
微博爬取完成，共爬取0条微博
信息抓取完毕

**Comment by dataabc** [comment]
原来是有的，是不是您不小心把config文件的对应参数删除了？
