### ISSUE TITLE
string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by JiangYue2003** [dataabc/weibo-crawler#373]
在下载蛇界猛女的图片的时候会有以下报错
string indices must be integers, not 'str'
Traceback (most recent call last):
  File "E:\weibo-crawler-master\weibo.py", line 854, in get_one_weibo
    weibo = self.parse_weibo(weibo_info)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\weibo-crawler-master\weibo.py", line 753, in parse_weibo
    weibo["pics"] = self.get_pics(weibo_info)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\weibo-crawler-master\weibo.py", line 427, in get_pics
    pic_list = [pic["large"]["url"] for pic in pic_info]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\weibo-crawler-master\weibo.py", line 427, in <listcomp>
    pic_list = [pic["large"]["url"] for pic in pic_info]
                ~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by JiangYue2003** [comment]
貌似是图片下载不下来，虽然报错之后程序依然在跑，但是根本无法下载到任何内容
这是我的config设置，另外还设置了我自己账号的cookie，数据库设置为默认
{
    "user_id_list": [
        "6020829791"
    ],
    "only_crawl_original": 0,
    "since_date": "2016-01-01",
    "start_page": 1,
    "write_mode": [
        "csv"
    ],
    "original_pic_download": 1,
    "retweet_pic_download": 0,
    "original_video_download": 1,
    "retweet_video_download": 0,
    "download_comment": 0,
    "comment_max_download_count": 100,
    "download_repost": 0,
    "repost_max_download_count": 100,
    "user_id_as_folder_name": 0,
    "remove_html_tag": 1,

**Comment by dataabc** [comment]
csv有图片地址吗？地址是有效的吗？

**Comment by JiangYue2003** [comment]
> csv有图片地址吗？地址是有效的吗？

没有，我这边仅仅有user.csv

**Comment by dataabc** [comment]
我最近没办法调试，您如果方便可以查看一下pic_info值，看是否是list格式，我不确定是不是程序问题还是之前的接口改变了。或者您尝试一下weibospider项目。

**Comment by JiangYue2003** [comment]
> 我最近没办法调试，您如果方便可以查看一下pic_info值，看是否是list格式，我不确定是不是程序问题还是之前的接口改变了。或者您尝试一下weibospider项目。

感谢老哥，你先忙，我不着急
