### ISSUE TITLE
'Error: ', KeyError('statuses_count',)

### ISSUE THREAD

**Issue by torizhao** [dataabc/weibo-crawler#5]
```
('Error: ', KeyError('statuses_count',))
Traceback (most recent call last):
  File "weibo.py", line 479, in start
    self.get_pages()
  File "weibo.py", line 452, in get_pages
    page_count = self.get_page_count()
  File "weibo.py", line 364, in get_page_count
    weibo_count = self.user['statuses_count']
KeyError: 'statuses_count'
```

这个微博已经炸号(但号主本人也就是我可以正常浏览）请问是否炸号有可能导致了该错误？

**Comment by dataabc** [comment]
这个错误说明没有提取到用户的信息。程序是通过<https://m.weibo.cn/api/container/getIndex?containerid=100505+user_id>这个连接提取用户信息的，如迪丽热巴的user_id是1669879400，程序通过<https://m.weibo.cn/api/container/getIndex?containerid=1005051669879400>提取她的信息。在浏览器的无痕模式，即浏览器没有记录你的微博cookie时，你可以把user_id替换成出错的微博id，尝试访问。如果没有获取有效信息，说明出错和目标微博炸号有关系。因为此方法可以在没有微博cookie时获取微博的信息，而这个微博如果不能获取，说明它和其它账号不一样，可能和炸号有关系。
