### ISSUE TITLE
您好，请问出现这样的错误显示该怎么解决呢？

### ISSUE THREAD

**Issue by kagawatryk** [dataabc/weibo-crawler#51]
Error:  list index out of range
Traceback (most recent call last):
  File "E:\weiboSpider.py", line 161, in extract_user_info
    if selector.xpath("//div[@class='tip'][2]/text()")[0] == u'学习经历':
IndexError: list index out of range
Error:  invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "E:\weiboSpider.py", line 254, in get_user
    weibo_num = int(user_info[0][3:-1])
ValueError: invalid literal for int() with base 10: ''

**Comment by dataabc** [comment]
如果方便，能否提供user_id，方便调试，谢谢

**Comment by kagawatryk** [comment]
> 如果方便，能否提供user_id，方便调试，谢谢

1005051747778640

**Comment by dataabc** [comment]
测试了下，没有复现错误，可以获取数据，猜测上述错误应该是被限制了，限制一段时间会自动解除限制。不知道是所有id都出错还是只这一个，还有这个账号过一段时间再试应该可以获取信息。

感谢反馈，如果有其它问题或建议，欢迎继续反馈

**Comment by kagawatryk** [comment]
非常感谢！之后又试了一次，能够成功抓取了。
