### ISSUE TITLE
3月12日最新版写入数据库提示出错

### ISSUE THREAD

**Issue by barnett2010** [dataabc/weibo-crawler#54]
mysql 提示写入成功，但是有error提示。
表里也有user weibo
但是和csv文件对比后发现。
表weibo里没有存到源微博文等相关的信息，

cmd里的代码如下

65条微博写入json文件完毕,保存路径:
C:\XXXX.json
Error:  (1406, "Data too long for column 'text' at row 1")
Traceback (most recent call last):
  File "weibo.py", line 840, in mysql_insert
    sql, [tuple(data.values()) for data in data_list])
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 199, in execute
many
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 199, in <genexp
r>
    self.rowcount = sum(self.execute(query, arg) for arg in args)
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 170, in execute

    result = self._query(query)
  File "C:\Anaconda3\lib\site-packages\pymysql\cursors.py", line 328, in _query
    conn.query(q)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 517, in que
ry
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 732, in _re
ad_query_result
    result.read()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 1075, in re
ad
    first_packet = self.connection._read_packet()
  File "C:\Anaconda3\lib\site-packages\pymysql\connections.py", line 684, in _re
ad_packet
    packet.check_error()
  File "C:\Anaconda3\lib\site-packages\pymysql\protocol.py", line 220, in check_
error
    err.raise_mysql_exception(self._data)
  File "C:\Anaconda3\lib\site-packages\pymysql\err.py", line 109, in raise_mysql
_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1406, "Data too long for column 'text' at row 1")
65条微博写入MySQL数据库完毕
微博爬取完成，共爬取65条微博
信息抓取完毕
********************************************************************************
********************

**Comment by barnett2010** [comment]
然后 搜索
Error: (1406, "Data too long for column 'text' at row 1")
这个报错，调了半天，没整明白，特来请教大佬

**Comment by dataabc** [comment]
这个错误说明微博文本太长，超过数据库的限制，可以修改weibo_to_mysql方法，把create_sql的text长度加长，原先是2000，修改这个数字就好

**Comment by barnett2010** [comment]
text varchar(20000),
---
Error:  (1074, "Column length too big for column 'text' (max = 16383); use BLOB
or TEXT instead")
--------------------------------------------------------------------

 text varchar(16000),
---
Error:  (1118, 'Row size too large. The maximum row size for the used table type
, not counting BLOBs, is 65535. This includes storage overhead, check the manual
. You have to change some columns to TEXT or BLOBs')

---------------------------------------------------
text varchar(10000),

68条微博写入MySQL数据库完毕
微博爬取完成，共爬取68条微博
信息抓取完毕

@databac 
感谢大佬的提示。。改了几个数字 ，发现不能改得太大。
1万多都是正常的。
数字太大无法正常生成weibo表。
