### ISSUE TITLE
出现错误

### ISSUE THREAD

**Issue by zzfiu** [dataabc/weibo-crawler#55]
****************************************************************************************************
原创部分：
微博id：4265722529605139
微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬 🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�微博正文：分享这 个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要 加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�Traceback (most recent call last):
  File "weibo.py", line 613, in get_one_page
    self.print_weibo(wb)
  File "weibo.py", line 533, in print_weibo
    self.print_one_weibo(weibo)
  File "weibo.py", line 513, in print_one_weibo
    print(u'微博正文：%s' % weibo['text'])
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1013, in start
    self.get_pages()
  File "weibo.py", line 960, in get_pages
    is_end = self.get_one_page(page)
  File "weibo.py", line 619, in get_one_page
    print("Error: ", e)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1037, in main
    wb.start()  # 爬取微博信息
  File "weibo.py", line 1019, in start
    print('Error: ', e)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1044, in <module>
    main()
  File "weibo.py", line 1039, in main
    print('Error: ', e)
OSError: [WinError 87] 参数错误。

微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 87] 参数错误。
微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�微博正文：分享这个酷酷的你//@李兰迪:🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬 🍬🍬分享一个需要加点糖的我.🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬🍬�🍬🍬🍬🍬🍬

**Comment by dataabc** [comment]
感谢反馈。

请问是通过命令行调用python运行的本程序，还是其它，是否更改过代码。网上类似的错误都是pytest、celery 等相关的，如果有类似的情况，可以按照网上对应的方法解决

**Comment by zzfiu** [comment]
命令行运行的，没改过代码

**Comment by dataabc** [comment]
把错误信息里面出现的print注释掉试试

**Comment by dataabc** [comment]
问题已经修复了。

这个问题应该与系统和python版本有关系，现在已经修复。

再次感谢反馈，如果有其它建议或问题，欢迎继续反馈:smile:
