### ISSUE TITLE
您好 用户爬虫发生如下错误

### ISSUE THREAD

**Issue by puppyK** [dataabc/weibo-crawler#60]
类型1 
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 142, in extract_user_info
    nickname = selector.xpath('//title/text()')[0]
AttributeError: 'NoneType' object has no attribute 'xpath'
Error:  'nickname'
Traceback (most recent call last):
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 260, in get_user
    self.print_user_info()
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 228, in print_user_info
    print(u'用户昵称: %s' % self.user['nickname'])
KeyError: 'nickname'

类型2 
Error:  'NoneType' object has no attribute 'xpath'
Traceback (most recent call last):
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 251, in get_user
    self.user['id'] = self.get_user_id(selector)
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 238, in get_user_id
    url_list = selector.xpath("//div[@class='u']//a")
AttributeError: 'NoneType' object has no attribute 'xpath'
Error:  'weibo_num'
Traceback (most recent call last):
  File "E:/微博数据/爬虫工具/weiboSpider-master/用户爬虫/weiboSpider（315.py", line 1054, in get_weibo_info
    if (self.user['weibo_num'] < 4000):  #微博博文数量小于
KeyError: 'weibo_num'

useridlist我设置了20多个人 只爬了不到1半 出错但是可以继续 好像爬取的不完整

**Comment by puppyK** [comment]
出错之后没进行改动 又F5运行了一次 这次没报错- - 爬取的用户也变多了

**Comment by puppyK** [comment]
有个问题 我在json文件中日期设定是since2020年1月16至今 可否设置一个阈值 如果1月16到至今发文数量少于20 就不爬取这个用户

**Comment by dataabc** [comment]
错误是因为被限制了，一段时间限制就自动解除了。可以通过降低爬取速度避免被限制，具体修改get_pages方法，
```
                    if (page -
                            page1) % random_pages == 0 and page < page_count:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上述表示每获取1到5页等待6到10秒，你可以适当加快暂停频率和加长等待时间。

可以设置阈值只是要改动较多的代码。因为1月16至今发的微博需要计算，所需的成本和之前差不多。微博每页10条，要想知道有没有20，只需要访问第二页的最后一条微博发布时间是不是满足since_date，需要访问一页网页。之前的代码是从第一页开始，如果满足since_date就继续，否则停止这个用户的爬取，对应少于20条的微博，最少访问一页，最多访问两页，差别不大。

**Comment by puppyK** [comment]
谢谢大佬回复！另外uid_list文件中如果有重复用户的话会重复爬取 应该做哪些修改呢

**Comment by dataabc** [comment]
不需要修改。

现在代码里有去重操作，读取user_id_list.txt文件，如果里面user_id和since_date组成的字典不在列表里才加入，否则就忽略了。例外情况是同一个用户出现多次，且since_date不同，这种情况是不过滤的。如果user_id_list.txt文件里都是user_id + 昵称的形式，没有单独设置since_date，这种情况也是能够过滤的

**Comment by puppyK** [comment]
json文件设置如下：

   "user_id_list": "user_id_list.txt",
    "filter": 1,
    "since_date": "2020-01-16",
    "write_mode": ["csv", "txt"],

user_id_list.txt内容如下：
6237031510 一个不想起名字的柚子
6391770079 晦涩蘑菇菌
6237031510 一个不想起名字的柚子

这样设置sincedata是一样的吧，但是内容出现了重复 重复的uid的csv文件里数据是重复的

**Comment by dataabc** [comment]
是否使用的是最新的程序，我测试了上面的user_id，可以过滤重复user_id。可能你用的不是最新的程序，把程序更新成最新的就行了

**Comment by puppyK** [comment]
谢谢您 确实没下载最新程序 之前我想着是 如果用户的总微博数超过4000 就跳过这个用户不爬取 您当时帮我修改的代码如下 。但是在新代码里我没找到这个区域，在新代码应该修改哪个区域呢

    def get_weibo_info(self):
        """获取微博信息"""
        try:
            url = 'https://weibo.cn/%s' % (self.user_config['user_uri'])
            selector = self.handle_html(url)
            self.get_user(selector)  # 获取用户信息、微博数、关注数、粉丝数
            if (self.user['weibo_num'] < 4000):  #微博博文数量小于

**Comment by dataabc** [comment]
就是修改get_weibo_info方法，改成这样：
```
    def get_weibo_info(self):
        """获取微博信息"""
        try:
            url = 'https://weibo.cn/%s' % (self.user_config['user_uri'])
            selector = self.handle_html(url)
            self.get_user(selector)  # 获取用户信息、微博数、关注数、粉丝数
            if (self.user['weibo_num'] < 4000):
                since_date = self.str_to_time(self.user_config['since_date'])
                now = datetime.now().strftime('%Y-%m-%d %H:%M')
                now = datetime.strptime(now, '%Y-%m-%d %H:%M')
                if since_date <= now:
                    page_num = self.get_page_num(selector)  # 获取微博总页数
                    wrote_num = 0
                    page1 = 0
                    random_pages = random.randint(1, 5)
                    self.start_time = datetime.now().strftime('%Y-%m-%d %H:%M')
                    for page in tqdm(range(1, page_num + 1), desc='Progress'):
                        is_end = self.get_one_page(page)  # 获取第page页的全部微博
                        if is_end:
                            break

                        if page % 20 == 0:  # 每爬20页写入一次文件
                            self.write_data(wrote_num)
                            wrote_num = self.got_num

                        # 通过加入随机等待避免被限制。爬虫速度过快容易被系统限制(一段时间后限
                        # 制会自动解除)，加入随机等待模拟人的操作，可降低被系统限制的风险。默
                        # 认是每爬取1到5页随机等待6到10秒，如果仍然被限，可适当增加sleep时间
                        if (page -
                                page1) % random_pages == 0 and page < page_num:
                            sleep(random.randint(6, 10))
                            page1 = page
                            random_pages = random.randint(1, 5)

                    self.write_data(wrote_num)  # 将剩余不足20页的微博写入文件
                if not self.filter:
                    print(u'共爬取' + str(self.got_num) + u'条微博')
                else:
                    print(u'共爬取' + str(self.got_num) + u'条原创微博')
        except Exception as e:
            print('Error: ', e)
            traceback.print_exc()
```

**Comment by puppyK** [comment]
这个代码之前给我发过，但是新版代码没有def get_weibo_info(self):这个模块 对应位置变成了    
def get_pages(self):
        """获取全部微博"""
        try:
            self.get_user_info()
            self.print_user_info()
            since_date = datetime.strptime(self.user_config['since_date'],
                                           '%Y-%m-%d')
            today = datetime.strptime(str(date.today()), '%Y-%m-%d')
            if since_date <= today:
                page_count = self.get_page_count()
                wrote_count = 0
                page1 = 0
                random_pages = random.randint(1, 5)
                self.start_date = datetime.now().strftime('%Y-%m-%d')
                for page in tqdm(range(1, page_count + 1), desc='Progress'):
                    is_end = self.get_one_page(page)
                    if is_end:
                        break

**Comment by dataabc** [comment]
get_weibo_info和get_pages，类似，前者是cookie版的，后者是免cookie版的，因为之前你用的是cookie版的，所以用cookie版修改的，如果是本项目，代码修改如下：
```
    def get_pages(self):
        """获取全部微博"""
        try:
            self.get_user_info()
            self.print_user_info()
            if self.user['statuses_count'] < 4000:
                since_date = datetime.strptime(self.user_config['since_date'],
                                               '%Y-%m-%d')
                today = datetime.strptime(str(date.today()), '%Y-%m-%d')
                if since_date <= today:
                    page_count = self.get_page_count()
                    wrote_count = 0
                    page1 = 0
                    random_pages = random.randint(1, 5)
                    self.start_date = datetime.now().strftime('%Y-%m-%d')
                    for page in tqdm(range(1, page_count + 1),
                                     desc='Progress'):
                        is_end = self.get_one_page(page)
                        if is_end:
                            break

                        if page % 20 == 0:  # 每爬20页写入一次文件
                            self.write_data(wrote_count)
                            wrote_count = self.got_count

                        # 通过加入随机等待避免被限制。爬虫速度过快容易被系统限制(一段时间后限
                        # 制会自动解除)，加入随机等待模拟人的操作，可降低被系统限制的风险。默
                        # 认是每爬取1到5页随机等待6到10秒，如果仍然被限，可适当增加sleep时间
                        if (page - page1
                            ) % random_pages == 0 and page < page_count:
                            sleep(random.randint(6, 10))
                            page1 = page
                            random_pages = random.randint(1, 5)

                    self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
                print(u'微博爬取完成，共爬取%d条微博' % self.got_count)
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()
```

**Comment by puppyK** [comment]
明白啦 成功运行 那如果在json文件的cookie位置加入我的cookie 是不是就变成了有cookie版的爬虫 可以爬取全部微博啦？

**Comment by dataabc** [comment]
是的。加入cookie就可以获取全部微博，免cookie版和cookie版的cookie是通用的，如果你之前用了cookie版，那它的cookie可以直接使用

**Comment by puppyK** [comment]
您好 我设置如下，但是list里爬几个用户之后总被限制。您看一下哪里设置不太合理    或者哪里可以降低一下爬取速度
 def get_pages(self):
        """获取全部微博"""
        try:
            self.get_user_info()
            self.print_user_info()
            if self.user['statuses_count'] < 5000:
                since_date = datetime.strptime(self.user_config['since_date'],
                                               '%Y-%m-%d')
                today = datetime.strptime(str(date.today()), '%Y-%m-%d')
                if since_date <= today:
                    page_count = self.get_page_count()
                    wrote_count = 0
                    page1 = 0
                    random_pages = random.randint(1, 5)
                    self.start_date = datetime.now().strftime('%Y-%m-%d')
                    for page in tqdm(range(1, page_count + 1),
                                     desc='Progress'):
                        is_end = self.get_one_page(page)
                        if is_end:
                            break

                        if page % 20 == 0:  # 每爬20页写入一次文件
                            self.write_data(wrote_count)
                            wrote_count = self.got_count

                    # 通过加入随机等待避免被限制。爬虫速度过快容易被系统限制(一段时间后限
                    # 制会自动解除)，加入随机等待模拟人的操作，可降低被系统限制的风险。默
                    # 认是每爬取1到5页随机等待6到10秒，如果仍然被限，可适当增加sleep时间
                    if (page -
                            page1) % random_pages == 0 and page < page_count:
                        sleep(random.randint(8, 15))
                        page1 = page
                        random_pages = random.randint(2, 5)

                self.write_data(wrote_count)  # 将剩余不足20页的微博写入文件
            print(u'微博爬取完成，共爬取%d条微博' % self.got_count)
        except Exception as e:
            print("Error: ", e)
            traceback.print_exc()

**Comment by dataabc** [comment]
```
                    if (page -
                            page1) % random_pages == 0 and page < page_count:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
就是控制微博页的速度控制的，看你上面代码已经改了，可能是再降低下速度才好，sleep越大等待的时间就越长，有利于降低被限制概率。random_pages越小sleep的等待次数就越大。如果仅从避免被限的角度讲，sleep越大越好，random_pages越小越好，但是这样速度会非常慢，所以要看你需求，综合考虑。
还有，上面的速度控制是控制**微博页**的访问。如果你不爬微博，而只爬用户信息，可以在get_pages方法的如下代码：
```
self.get_user_info()
```
之后加上随机等待，如：
```
self.get_user_info()
sleep(random.randint(3, 6))
```

**Comment by xm634634** [comment]
> ```
>                     if (page -
>                             page1) % random_pages == 0 and page < page_count:
>                         sleep(random.randint(6, 10))
>                         page1 = page
>                         random_pages = random.randint(1, 5)
> ```
> 
> 就是控制微博页的速度控制的，看你上面代码已经改了，可能是再降低下速度才好，sleep越大等待的时间就越长，有利于降低被限制概率。random_pages越小sleep的等待次数就越大。如果仅从避免被限的角度讲，sleep越大越好，random_pages越小越好，但是这样速度会非常慢，所以要看你需求，综合考虑。
> 还有，上面的速度控制是控制**微博页**的访问。如果你不爬微博，而只爬用户信息，可以在get_pages方法的如下代码：
> 
> ```
> self.get_user_info()
> ```
> 
> 之后加上随机等待，如：
> 
> ```
> self.get_user_info()
> sleep(random.randint(3, 6))
> ```

Mark～
这个管用
