### ISSUE TITLE
抓取错误 OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by lovecn** [dataabc/weibo-crawler#73]
依赖包都安装了，但还是失败了。
```js
λ python weibo.py
Error:  HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=1005051629810574 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()
  File "D:\python\lib\site-packages\OpenSSL\SSL.py", line 1907, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "D:\python\lib\site-packages\OpenSSL\SSL.py", line 1639, in _raise_ssl_error
    _raise_current_error()
  File "D:\python\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 805, in _prepare_proxy
    conn.connect()
  File "D:\python\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "D:\python\lib\site-packages\urllib3\util\ssl_.py", line 347, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\python\lib\site-packages\urllib3\contrib\pyopenssl.py", line 462, in wrap_socket
    raise ssl.SSLError('bad handshake: %r' % e)
ssl.SSLError: ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\python\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\python\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=1005051629810574 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 982, in get_pages
    self.get_user_info()
  File "weibo.py", line 206, in get_user_info
    js = self.get_json(params)
  File "weibo.py", line 116, in get_json
    r = requests.get(url, params=params, cookies=self.cookie)
  File "D:\python\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "D:\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\python\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\python\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=1005051629810574 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))
信息抓取完毕
****************************************************************************************************

```

**Comment by dataabc** [comment]
感谢反馈。

可以给出错的requests语句添加verify=False参数来解决。

**Comment by lovecn** [comment]
@dataabc 感谢回复，为什么你代码里没加这个也能正常运行呢

**Comment by dataabc** [comment]
感觉可能和你的运行环境如编码之类的有关，我用win10和Ubuntu都可以运行

**Comment by Thendytx** [comment]
> 
> 
> 感谢反馈。
> 
> 可以给出错的requests语句添加verify=False参数来解决。

您好，我遇到一个类似的问题，ssl握手时失败，“ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)”


下面说重试次数达到上限“    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=2302831669879400_-_INFO (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)')))”


最下面的报错是request时的SSLError“lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=2302831669879400_-_INFO (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)')))”




全部日志信息如下
2021-07-13 10:23:48,850 - ERROR - HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=2302831669879400_-_INFO (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)')))
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\util\ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda3\envs\pytorch\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda3\envs\pytorch\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "D:\Anaconda3\envs\pytorch\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\urllib3\util\retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=2302831669879400_-_INFO (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1519, in get_pages
    self.get_user_info()
  File "weibo.py", line 288, in get_user_info
    js = self.get_json(params)
  File "weibo.py", line 168, in get_json
    r = requests.get(url,
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda3\envs\pytorch\lib\site-packages\requests\adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='m.weibo.cn', port=443): Max retries exceeded with url: /api/container/getIndex?containerid=2302831669879400_-_INFO (Caused by SSLError(SSLError(1, '[SSL: BAD_SIGNATURE] bad signature (_ssl.c:1123)')))
2021-07-13 10:23:48,908 - INFO - 信息抓取完毕
2021-07-13 10:23:48,914 - INFO - ****************************************************************************************************



从上面能看到最后一个报错是在168行的requests，这里的参数已经有verify=False了，为什么也是错误的呢？如果您知道的话，望解答

**Comment by dataabc** [comment]
@Thendytx 
一直是这个错误吗，还是之前没错运行一段时间后出错？如果是后者，过一段时间再试，可能暂时被禁了。

**Comment by Thendytx** [comment]
> 
> 
> @Thendytx
> 一直是这个错误吗，还是之前没错运行一段时间后出错？如果是后者，过一段时间再试，可能暂时被禁了。

对不起一直没有回复
这个错误是第一次在windows上运行时出现的，试了下放到linux服务器上跑就没问题了

**Comment by dataabc** [comment]
@Thendytx 
客气了，windows上猜测可能和SSL有关

**Comment by tanmx** [comment]
参考这篇文章解决问题：https://blog.csdn.net/u011426236/article/details/88864469
