### ISSUE TITLE
大佬，爬取不到一半微博就出现失败

### ISSUE THREAD

**Issue by bijiamo** [dataabc/weibo-crawler#75]
大佬，我尝试抓取1669879400 Dear-迪丽热巴出现以下错误
已经设置6到20秒的等待了
if (page -
        page1) % random_pages == 0 and page < page_count:
    sleep(random.randint(6 20))
    page1 = page
    random_pages = random.randint(1, 5)
还是失败！
下载的是最新的程序。
其他没修改，错误能重复出现，基本都是抓到第6页出现错误。
希望大佬指导。
***********************************************************************
原创部分：
微博id：4396056907479207
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
Traceback (most recent call last):
  File "weibo.py", line 635, in get_one_page
    self.print_weibo(wb)
  File "weibo.py", line 556, in print_weibo
    print('-' * 120)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 995, in get_pages
    is_end = self.get_one_page(page)
  File "weibo.py", line 643, in get_one_page
    print("Error: ", e)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1053, in start
    self.get_pages()
  File "weibo.py", line 1015, in get_pages
    print("Error: ", e)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1077, in main
    wb.start()  # 爬取微博信息
  File "weibo.py", line 1059, in start
    print('Error: ', e)
OSError: [WinError 87] 参数错误。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weibo.py", line 1084, in <module>
    main()
  File "weibo.py", line 1079, in main
    print('Error: ', e)
OSError: [WinError 87] 参数错误。

微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 87] 参数错误。
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
微博正文：很高兴成为百雀羚的彩妆代言人！东方草本能量亦妆亦养，让你自带滤镜，轻松get桃花颜，快来看 @百雀羚 为大家揭晓桃花肌秘吧！��
****************************************************************************

**Comment by dataabc** [comment]
感谢反馈。

刚刚测试了下，没有复现问题。之前出过类型问题，因为内容中有些无法打印的内容，导致打印出错，不知道是不是相同原因，你可以修改print_weibo方法为如下内容，
```
    def print_weibo(self, weibo):
        """打印微博，若为转发微博，会同时打印原创和转发部分"""
        try:
            if weibo.get('retweet'):
                print('*' * 100)
                print(u'转发部分：')
                self.print_one_weibo(weibo['retweet'])
                print('*' * 100)
                print(u'原创部分：')
            self.print_one_weibo(weibo)
            print('-' * 120)
        except OSError:
            pass
```

如果还有问题，欢迎继续反馈。

**Comment by bijiamo** [comment]
感谢大佬指点！！问题已经解决。enjoy！！
