### ISSUE TITLE
您好，请教下user_id_list中账号较多时，只能爬取几个用户程序就失败的问题

### ISSUE THREAD

**Issue by candyczy2** [dataabc/weibo-crawler#78]
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
用户信息
Error:  'id'
信息抓取完毕
****************************************************************************************************
Traceback (most recent call last):
  File "E:/Python/Py Files/WeiboSpider-master/dataabc/weibo.py", line 983, in get_pages
    self.print_user_info()
  File "E:/Python/Py Files/WeiboSpider-master/dataabc/weibo.py", line 510, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'

user_id_list中前几个用户的爬取是正常的，后面的就一直报这个错误，想请问下应该怎么修改，是哪里出了问题？谢谢！

**Comment by candyczy2** [comment]
我的user_id_list是这种格式：
[ "1025954121", "1033525837", "1055906754", "1153193392", "1167384404", "1180146333", "1184070324", "1215041654", "1223185337", "1250316555", "1259131430", "1285381255", "1288120802", "1292637645", "1293601724", "1301181307", "1400619031", "1420072070", "1429269277", "1435577133", "1450577630", "1478747981", "1544850435", "1549300595", "1563245477", "1567701471", "1573213874", "1588534483", "1588852725", "1610832234", "1611230145", "1615504643", "1621029982", "1628093062", "1636485172", "1644572057", "1653791034", "1660097717", "1661567270", "1664055474", "1664792722", "1669790423", "1674689684", "1678865607", "1691685012", "1692214833", "1692549487", "1703582372", "1707521815", "1711170927", "1711603430", "1715481564", "1722147131", "1725521490", "1733407015", "1737069930", "1739781650", "1741566482", "1747632103", "1752663961", "1760569670", "1761631442", "1764727842", "1765500562", "1769293612", "1770667315", "1772305767", "1773044695", "1780595185", "1781201515", "1788570493", "1790121890", "1790946257", "1791697355", "1793186310", "1793381731", "1796264654", "1806721067", "1819431887", "1825714831", "1826881071", "1829762945", "1830121650", "1835010591", "1841523415", "1842902030", "1852150370", "1854847693", "1862688872", "1868643113", "1870586140", "1878707982", "1880061615", "1881343174", "1891846693", "1894023475", "1897826531", "1903080347", "1905983367"]

**Comment by dataabc** [comment]
感谢反馈。

说明被限制了，一段时间限制会自动解除。可以通过降低爬取速度避免被限，具体修改get_page方法：
```
                    if (page -
                            page1) % random_pages == 0 and page < page_count:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面代表每1到5页sleep 6到10秒，你可以缩短sleep频率或增加sleep时间避免被限。

**Comment by candyczy2** [comment]
> 感谢反馈。
> 
> 说明被限制了，一段时间限制会自动解除。可以通过降低爬取速度避免被限，具体修改get_page方法：
> 
> ```
>                     if (page -
>                             page1) % random_pages == 0 and page < page_count:
>                         sleep(random.randint(6, 10))
>                         page1 = page
>                         random_pages = random.randint(1, 5)
> ```
> 
> 上面代表每1到5页sleep 6到10秒，你可以缩短sleep频率或增加sleep时间避免被限。

谢谢！我去试试

**Comment by lplpjjj** [comment]
> 感谢反馈。
> 
> 说明被限制了，一段时间限制会自动解除。可以通过降低爬取速度避免被限，具体修改get_page方法：
> 
> ```
>                     if (page -
>                             page1) % random_pages == 0 and page < page_count:
>                         sleep(random.randint(6, 10))
>                         page1 = page
>                         random_pages = random.randint(1, 5)
> ```
> 
> 上面代表每1到5页sleep 6到10秒，你可以缩短sleep频率或增加sleep时间避免被限。

您好，我也遇到了同样的error信息，然后我按照你的建议把sleep频率改到了1到2页sleep 30 到60秒，但是还是出现这个报错，而且我目前在config.jason里只set了一个id，这种情况应该怎么解决呢？

**Comment by dataabc** [comment]
@lplpjjj 
可能被限制了，一段时间后限制自动解除，可以过一段时间（几个小时）再运行。

**Comment by lplpjjj** [comment]
> @lplpjjj
> 可能被限制了，一段时间后限制自动解除，可以过一段时间（几个小时）再运行。

哦哦 好的 谢谢你！
