### ISSUE TITLE
报错：使用txt文件读取用户id时程序中断

### ISSUE THREAD

**Issue by clayonesss** [dataabc/weibo-crawler#79]
用户信息
Error:  'id'
Traceback (most recent call last):
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 983, in get_pages
    self.print_user_info()
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 510, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'
信息抓取完毕
****************************************************************************************************
Error:  'screen_name'
Traceback (most recent call last):
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 1056, in start
    self.update_user_config_file(self.user_config_file_path)
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 947, in update_user_config_file
    info.append(self.user['screen_name'])
KeyError: 'screen_name'

中断的txt文本如下
7140736952
7129483834
7126624443
7126240787
7112729932
7097616757
7073823056
7047463567
7045067283
7033667346
7030999415
7026776888
7026620274
7019993681
7019866067
7018961673

不知道是不是用户id不标准的问题，一部分用户id为6-8位数的也会出现类似错误

**Comment by dataabc** [comment]
感谢反馈。

出现这个错误有两种可能：
1.user_id不正确，txt文件中的部分id可能是错误的，比如个性域名等，导致出错。对于这类错误，本程序会跳过。如果一定要获得那些出错的微博信息，可以使用cookie版（https://github.com/dataabc/weiboSpider），它可以正确处理id为个性域名等的情况；
2.被限制了，限制在一段时间会自动解除。可以通过降低速度避免被限制，修改get_pages方法：
```
                    if (page -
                            page1) % random_pages == 0 and page < page_count:
                        sleep(random.randint(6, 10))
                        page1 = page
                        random_pages = random.randint(1, 5)
```
上面表示每隔1到5页等待6到10秒，可以缩短等待频率或者增加等待时间降低被限概率。

**Comment by clayonesss** [comment]
非常感谢！！
因为只爬取了微博用户信息，而并没有爬取微博博文内容，所以可能是user_id不正确。
将user_id文件中去除了非数字id后，大量爬取用户信息（约150名用户左右）
出现了新的错误
Error:  Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 982, in get_pages
    self.get_user_info()
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 206, in get_user_info
    js = self.get_json(params)
  File "D:/爬虫测试/weibo-crawler/weibo.py", line 117, in get_json
    return r.json()
  File "D:\app\anaconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\app\anaconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\app\anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\app\anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by clayonesss** [comment]
非常感谢！

测试的一次爬取id数量为700个。
对于错误1，剔除了非数字id后，仍然会出现上述错误。
我想可能是被限制了。在设置只爬取微博用户信息后，大约在获取150~240个用户信息后仍然会出现上述错误。不知道能否在爬取微博用户信息时，也降低速度？

**Comment by dataabc** [comment]
是的，如果只爬用户信息，需要在start方法也降速，随机sleep

**Comment by clayonesss** [comment]
> 是的，如果只爬用户信息，需要在start方法也降速，随机sleep

非常感谢！！

**Comment by Shimon-Guo** [comment]
微博数量很多的id，在爬取过程中最后一部分可能会被限制，导致爬取的内容为空，所以会出现以下错误，建议出错的数据可以跳过。
Error:  'id'
Traceback (most recent call last):
  File "weibo.py", line 977, in start
    self.get_pages()
  File "weibo.py", line 913, in get_pages
    self.print_user_info()
  File "weibo.py", line 461, in print_user_info
    print(u'用户id：%s' % self.user['id'])
KeyError: 'id'

**Comment by dataabc** [comment]
@Shimon-Guo 
感谢建议。
