### ISSUE TITLE
您好，有两个错误，一个是下载图片过程中，一个是下载博文过程中，方便看一下？

### ISSUE THREAD

**Issue by scottieshushushu** [dataabc/weibo-crawler#81]
下载博文中出现：
Error:  invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "weibo.py", line 579, in get_one_weibo
    retweet = self.parse_weibo(retweeted_status)
  File "weibo.py", line 486, in parse_weibo
    weibo['id'] = int(weibo_info['id'])
ValueError: invalid literal for int() with base 10: ''

下载图片过程中出现：
Download progress:   0%|                                                                        | 0/62 [00:00<?, ?it/s]Error:  [Errno 2] No such file or directory: 'C:\\Users\\【此处码掉电脑用户名】\\weibo\\【此处码掉weibo用户名】\\img\\原创微博图片\\20100627_20110062752260571.cn/large/4955695ct89f15d5aaba9&690'
Traceback (most recent call last):
  File "weibo.py", line 323, in download_one_file
    with open(file_path, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\【此处码掉电脑用户名】\\weibo\\【此处码掉weibo用户名】\\img\\原创微博图片\\20100627_20110062752260571.cn/large/4955695ct89f15d5aaba9&690'

看了下前面没有类似问题，能帮忙看看怎么解决吗，谢谢呀

**Comment by dataabc** [comment]
感谢反馈。

第一个错误以前出现过，应该是获取到了微博，但是微博id为空，所以出错了，不知道为什么会出现这个错误。隔一会再运行就没有错了。

第二个错误很奇怪，能否提供出错的微博id，方便调试

**Comment by scottieshushushu** [comment]
id是1230334300，我只筛了原创。但筛了全部微博，从10年到现在，是否早期微博图片跟现在有什么格式不同？我看也是10年的内容才开始出现这个错误的（不过中途有过那个需要改暂停秒数的问题导致没有筛出结果，不知道跳过的部分是否也有这种情况）。

**Comment by dataabc** [comment]
第一个问题已经修复，原因是有一些转发微博，转发理由还在，被转发的内容已经不可见了，所以出错。
第二个问题正在解决。

**Comment by dataabc** [comment]
第二个问题已经修复。出错原因是某些图片不以图片类型结尾，如“.jpg”、“.gif”等，导致出错，现已修复。

如果还有其它问题，欢迎继续反馈
