### ISSUE TITLE
您好，请问出现错误Error:  [Errno 13] Permission denied该怎么办？

### ISSUE THREAD

**Issue by hjw459** [dataabc/weibo-crawler#85]
按照代码抓取全部微博但是抓到20页就开始出现这个错误了
------------------------------已获取西贝莜面村(1904039151)的第20页微博------------------------------
Error:  [Errno 13] Permission denied: 'C:\\Users\\61731\\Desktop\\weibo-crawler-master\\weibo\\西贝莜面村\\1904039151.csv'
Traceback (most recent call last):
  File "weibo.py", line 1019, in get_pages
    self.write_data(wrote_count)
  File "weibo.py", line 982, in write_data
    self.write_csv(wrote_count)
  File "weibo.py", line 742, in write_csv
    self.csv_helper(result_headers, result_data, file_path)
  File "weibo.py", line 758, in csv_helper
    with open(file_path, 'a', encoding='utf-8-sig', newline='') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\61731\\Desktop\\weibo-crawler-master\\weibo\\西贝莜面村\\1904039151.csv'
信息抓取完毕
****************************************************************************************************

**Comment by dataabc** [comment]
感谢反馈。

出现这个错误可能原因是在程序运行时你可能手动打开了要写入的csv文件，这时是无法写入csv的，关掉打开的文件程序运行程序就好
