### ISSUE TITLE
能否部署多个程序同时运行，批量工作

### ISSUE THREAD

**Issue by PhoebusSi** [dataabc/weibo-crawler#95]
目前同时工作两个，但是当第二个工作一段时间后，两个程序同时遇到了这个问题：
Traceback (most recent call last):
  File "weibo.py", line 628, in get_one_page
    js = self.get_weibo_json(page)
  File "weibo.py", line 125, in get_weibo_json
    js = self.get_json(params)
  File "weibo.py", line 117, in get_json
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
^MProgress:   1%|          | 2/243 [00:00<00:13, 17.55it/s]Traceback (most recent call last):
  File "weibo.py", line 628, in get_one_page
    js = self.get_weibo_json(page)
  File "weibo.py", line 125, in get_weibo_json
    js = self.get_json(params)
  File "weibo.py", line 117, in get_json
    return r.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
程序没有终止，而是从1%到100%，然后好像又从0%开始。
不知道是否是因为我同时运行两个程序造成的，均为不使用cookie。
如果我要部署多个程序同时运行，需要什么条件，需要用不同的ip吗？

**Comment by dataabc** [comment]
感谢反馈。

不支持同时运行多个程序。本程序只是模仿一个用户服务微博，为想手动获取微博的用户提供便利。如果多个程序同时运行，可能会增加对方服务器的压力，考虑到道德原因，不支持这种方式，感谢理解。
